[[main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1

[[main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications"
    weight = 2

[[main]]
    identifier = "cv"
    name = "CV"
    url = "/cv"
    weight = 3


# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/saraoe"
    weight = 1

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/smoestergaard"
    weight = 2

[[social]]
    identifier = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/sara-m%C3%B8ller-%C3%B8stergaard-14025a193/"
    weight = 3